ALTER TABLE users ADD COLUMN IF NOT EXISTS headline     VARCHAR(60);
ALTER TABLE users ADD COLUMN IF NOT EXISTS biography    TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS language     VARCHAR(10) DEFAULT 'vi';
ALTER TABLE users ADD COLUMN IF NOT EXISTS website      VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS facebook     VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS instagram    VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin     VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS tiktok       VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS github       VARCHAR(255);
